### ISSUE TITLE
LauncherProfileIcon of furnace becomes NULL when using ProfileManager.toJson()

### ISSUE THREAD

**Issue by dusmartijngames** [dedepete/dotMCLauncher#7]
When using ProfileManager.toJson() my Furnace profile icon becomes Null. This seems to be because of the missing Furnace case in LauncherProfileIcon.GetIcon() and LauncherProfileIcon.GetString()

**Comment by dedepete** [comment]
Thank you for your contribution! I'm not able to keep up with official launcher's updates so I believe there's quite a few missing icons besides a furnace's one. 
Awaiting for the requested change and I will merge your pull request.
